export const CUSTOMER_ADD_WALLET_REQUEST = "CUSTOMER_ADD_WALLET_REQUEST"
export const CUSTOMER_ADD_WALLET_SUCCESS = "CUSTOMER_ADD_WALLET_SUCCESS"
export const CUSTOMER_ADD_WALLET_FAIL = "CUSTOMER_ADD_WALLET_FAIL"

export const BLOCK_CUSTOMER_REQUEST = "BLOCK_CUSTOMER_REQUEST"
export const BLOCK_CUSTOMER_SUCCESS = "BLOCK_CUSTOMER_SUCCESS"
export const BLOCK_CUSTOMER_FAIL = "BLOCK_CUSTOMER_FAIL"

export const UNBLOCK_CUSTOMER_REQUEST = "UNBLOCK_CUSTOMER_REQUEST"
export const UNBLOCK_CUSTOMER_SUCCESS = "UNBLOCK_CUSTOMER_SUCCESS"
export const UNBLOCK_CUSTOMER_FAIL = "UNBLOCK_CUSTOMER_FAIL"

export const DRIVER_ADD_WALLET_REQUEST = "DRIVER_ADD_WALLET_REQUEST"
export const DRIVER_ADD_WALLET_SUCCESS = "DRIVER_ADD_WALLET_SUCCESS"
export const DRIVER_ADD_WALLET_FAIL = "DRIVER_ADD_WALLET_FAIL"

export const DRIVER_ADD_COMMENT_REQUEST = "DRIVER_ADD_COMMENT_REQUEST"
export const DRIVER_ADD_COMMENT_SUCCESS = "DRIVER_ADD_COMMENT_SUCCESS"
export const DRIVER_ADD_COMMENT_FAIL = "DRIVER_ADD_COMMENT_FAIL"

export const UPDATE_DRIVER_PERSONAL_DETAILS_REQUEST = "UPDATE_DRIVER_PERSONAL_DETAILS_REQUEST"
export const UPDATE_DRIVER_PERSONAL_DETAILS_SUCCESS = "UPDATE_DRIVER_PERSONAL_DETAILS_SUCCESS"
export const UPDATE_DRIVER_PERSONAL_DETAILS_FAIL = "UPDATE_DRIVER_PERSONAL_DETAILS_FAIL"