export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN-REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN-SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN-FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const SUB_ADMIN_LOGIN_REQUEST = 'SUB_ADMIN_LOGIN-REQUEST';
export const SUB_ADMIN_LOGIN_SUCCESS = 'SUB_ADMIN_LOGIN-SUCCESS';
export const SUB_ADMIN_LOGIN_FAIL = 'SUB_ADMIN_LOGIN-FAIL';
export const SUB_ADMIN_LOGOUT = 'SUB_ADMIN_LOGOUT';

export const CUSTOMERS_LIST_REQUEST = 'CUSTOMERS_LIST_REQUEST';
export const CUSTOMERS_LIST_SUCCESS = 'CUSTOMERS_LIST_SUCCESS';
export const CUSTOMERS_LIST_FAIL = 'CUSTOMERS_LIST_FAIL';

export const CUSTOMER_ADD_COMMENT_REQUEST = "CUSTOMER_ADD_COMMENT_REQUEST"
export const CUSTOMER_ADD_COMMENT_SUCCESS = "CUSTOMER_ADD_COMMENT_SUCCESS"
export const CUSTOMER_ADD_COMMENT_FAIL = "CUSTOMER_ADD_COMMENT_FAIL"

export const SINGLE_CUSTOMER_DETAILS_REQUEST = "SINGLE_CUSTOMER_DETAILS_REQUEST"
export const SINGLE_CUSTOMER_DETAILS_SUCCESS = "SINGLE_CUSTOMER_DETAILS_SUCCESS"
export const SINGLE_CUSTOMER_DETAILS_FAIL = "SINGLE_CUSTOMER_DETAILS_FAIL"


export const DRIVERS_LIST_REQUEST = "DRIVERS_LIST_REQUEST"
export const DRIVERS_LIST_SUCCESS = "DRIVERS_LIST_SUCCESS"
export const DRIVERS_LIST_FAIL = "DRIVERS_LIST_FAIL"

export const SINGLE_DRIVER_DETAILS_REQUEST = "SINGLE_DRIVER_DETAILS_REQUEST"
export const SINGLE_DRIVER_DETAILS_SUCCESS = "SINGLE_DRIVER_DETAILS_SUCCESS"
export const SINGLE_DRIVER_DETAILS_FAIL = "SINGLE_DRIVER_DETAILS_FAIL"




